import type { Metadata } from "next";
import { Inter} from "next/font/google"
import "./globals.css";
import { NextAuthProvider } from "../provider";
import { AppClient } from "../components/AppBarClient";


const intert = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={intert.className}>
        <NextAuthProvider>
          <AppClient/>
          {children}
        </NextAuthProvider>
     
      </body>
    </html>
  );
}
